## Database descriptions


### Short database description "Computer firm"

The database scheme consists of four tables:
Product(maker, model, type)
PC(code, model, speed, ram, hd, cd, price)
Laptop(code, model, speed, ram, hd, screen, price)
Printer(code, model, color, type, price)
The Product table contains data on the maker, model number, and type of product ('PC', 'Laptop', or 'Printer'). It is assumed that model numbers in the Product table are unique for all makers and product types. Each personal computer in the PC table is unambiguously identified by a unique code, and is additionally characterized by its model (foreign key referring to the Product table), processor speed (in MHz) – speed field, RAM capacity (in Mb) - ram, hard disk drive capacity (in Gb) – hd, CD-ROM speed (e.g, '4x') - cd, and its price. The Laptop table is similar to the PC table, except that instead of the CD-ROM speed, it contains the screen size (in inches) – screen. For each printer model in the Printer table, its output type (‘y’ for color and ‘n’ for monochrome) – color field, printing technology ('Laser', 'Jet', or 'Matrix') – type, and price are specified. 

### Short database description "Ships"

The database of naval ships that took part in World War II is under consideration. The database consists of the following relations: 
Classes(class, type, country, numGuns, bore, displacement) 
Ships(name, class, launched) 
Battles(name, date) 
Outcomes(ship, battle, result) 
Ships in classes all have the same general design. A class is normally assigned either the name of the first ship built according to the corresponding design, or a name that is different from any ship name in the database. The ship whose name is assigned to a class is called a lead ship.
The Classes relation includes the name of the class, type (can be either bb for a battle ship, or bc for a battle cruiser), country the ship was built in, the number of main guns, gun caliber (bore diameter in inches), and displacement (weight in tons). The Ships relation holds information about the ship name, the name of its corresponding class, and the year the ship was launched. The Battles relation contains names and dates of battles the ships participated in, and the Outcomes relation - the battle result for a given ship (may be sunk, damaged, or OK, the last value meaning the ship survived the battle unharmed). 
Notes: 1) The Outcomes relation may contain ships not present in the Ships relation. 2) A ship sunk can’t participate in later battles. 3) For historical reasons, lead ships are referred to as head ships in many exercises.4) A ship found in the Outcomes table but not in the Ships table is still considered in the database. This is true even if it is sunk. 

### Short database description "Recycling firm"

The firm owns several buy-back centers for collection of recyclable materials. Each of them receives funds to be paid to the recyclables suppliers. Data on funds received is recorded in the table 
Income_o(point, date, inc)
The primary key is (point, date), where point holds the identifier of the buy-back center, and date corresponds to the calendar date the funds were received. The date column doesn’t include the time part, thus, money (inc) arrives no more than once a day for each center. Information on payments to the recyclables suppliers is held in the table
Outcome_o(point, date, out)
In this table, the primary key (point, date) ensures each buy-back center reports about payments (out) no more than once a day, too. 
For the case income and expenditure may occur more than once a day, another database schema with tables having a primary key consisting of the single column code is used:
Income(code, point, date, inc)
Outcome(code, point, date, out)
Here, the date column doesn’t include the time part, either. 

### Short database description "Painting"

The database schema consists of 3 tables:
utQ (Q_ID int, Q_NAME varchar(35)), utV (V_ID int, V_NAME varchar(35), V_COLOR char(1)), utB (B_DATETIME datetime, B_Q_ID int, B_V_ID int, B_VOL tinyint).
The utQ table contains the identifiers and names of squares, the initial color of which is black. (Note: black is not a color and is considered unpainted. Only Red, Green and Blue are colors.) 
The utV table contains the identifiers and names of spray cans and the color of paint they are filled with.
The utB table holds information on squares being spray-painted, and contains the time of the painting event, the square and spray can identifiers, the quantity of paint being applied.
It should be noted that
- a spray can may contain paint of one of three colors: red (V_COLOR='R'), green (V_COLOR='G'), or blue (V_COLOR='B');
- any spray can initially contains 255 units of paint;
- the square color is defined in accordance with the RGB model, i.e. R=0, G=0, B=0 is black, whereas R=255, G=255, B=255 is white;
- any record in the utB table decreases the paint quantity in the corresponding spray can by B_VOL and accordingly increases the amount of paint applied to the square by the same value;
- B_VOL must be greater than 0 and less or equal to 255;
- the paint quantity of a single color applied to one square can’t exceed 255, and there can’t be a less than zero amount of paint in a spray can;
- the time of the painting event (B_DATETIME) is specified with one second precision, i.e. it does not contain milliseconds;
- for historical reasons, the spray cans are referred to as “balloons” by many of the exercises, and the utV table contains spray can names (V_NAME column) such as “Balloon # 01”, etc.

## SQL connection

In [1]:
import sqlalchemy as sa
engine = sa.create_engine('postgresql://postgres:*****@localhost:5432/postgres')
%load_ext sql
%sql $engine.url

## Exercises

### Exercise: 1 (Serge I: 2002-09-30)

#### DB: "Computer firm"

Find the model number, speed and hard drive capacity for all the PCs with prices below $500.
Result set: model, speed, hd.

In [2]:
%%sql SELECT model, speed, hd 
FROM pc 
WHERE price < 500;

 * postgresql://postgres:***@localhost:5432/postgres
4 rows affected.


[('1232', 500, 10.0),
 ('1232', 450, 8.0),
 ('1232', 450, 10.0),
 ('1260', 500, 10.0)]

### Exercise: 2 (Serge I: 2002-09-21)

#### DB: "Computer firm"

List all printer makers. Result set: maker.

In [3]:
%%sql SELECT DISTINCT maker
FROM product
WHERE type = 'Printer';

 * postgresql://postgres:***@localhost:5432/postgres
3 rows affected.


[('A',), ('D',), ('E',)]

### Exercise: 3 (Serge I: 2002-09-30)

#### DB: "Computer firm"

Find the model number, RAM and screen size of the laptops with prices over $1000.

In [4]:
%%sql SELECT model, ram, screen 
FROM laptop 
WHERE price > 1000;

 * postgresql://postgres:***@localhost:5432/postgres
3 rows affected.


[('1750', 128, 14), ('1298', 64, 15), ('1752', 128, 14)]

### Exercise: 4 (Serge I: 2002-09-21)

#### DB: "Computer firm"

Find all records from the Printer table containing data about color printers.

In [5]:
%%sql SELECT * 
FROM printer 
WHERE color = 'y';

 * postgresql://postgres:***@localhost:5432/postgres
2 rows affected.


[(2, '1433', 'y', 'Jet', Decimal('270.00')),
 (3, '1434', 'y', 'Jet', Decimal('290.00'))]

### Exercise: 5 (Serge I: 2002-09-30)

#### DB: "Computer firm"

Find the model number, speed and hard drive capacity of PCs cheaper than $600 having a 12x or a 24x CD drive.

In [6]:
%%sql SELECT PC.model, PC.speed, PC.hd
FROM PC WHERE
PC.cd IN ('12x','24x')
AND PC.price < 600;

 * postgresql://postgres:***@localhost:5432/postgres
4 rows affected.


[('1232', 500, 10.0),
 ('1232', 450, 8.0),
 ('1232', 450, 10.0),
 ('1260', 500, 10.0)]

### Exercise: 6 (Serge I: 2002-10-28)

#### DB: "Computer firm"

For each maker producing laptops with a hard drive capacity of 10 Gb or higher, find the speed of such laptops. Result set: maker, speed.

In [7]:
%%sql SELECT DISTINCT Product.maker, Laptop.speed 
FROM Laptop
JOIN
Product ON Product.model = Laptop.model
WHERE hd >= 10;

 * postgresql://postgres:***@localhost:5432/postgres
4 rows affected.


[('A', 750), ('A', 450), ('A', 600), ('B', 750)]

### Exercise: 7 (Serge I: 2002-11-02)

#### DB: "Computer firm"

Get the models and prices for all commercially available products (of any type) produced by maker B.

In [8]:
%%sql SELECT PC.model, PC.price
FROM PC
JOIN
Product ON PC.model = Product.model
WHERE Product.maker = 'B'
UNION
SELECT Laptop.model, Laptop.price
FROM Laptop
JOIN
Product ON Laptop.model = Product.model
WHERE Product.maker = 'B'
UNION
SELECT Printer.model, Printer.price
FROM Printer
JOIN
Product ON Printer.model = Product.model
WHERE Product.maker = 'B';

 * postgresql://postgres:***@localhost:5432/postgres
2 rows affected.


[('1750', Decimal('1200.00')), ('1121', Decimal('850.00'))]

### Exercise: 8 (Serge I: 2003-02-03)

#### DB: "Computer firm"

Find the makers producing PCs but not laptops.

In [9]:
%%sql SELECT maker
FROM Product
WHERE type = 'PC'
EXCEPT
SELECT maker
FROM Product 
WHERE type = 'Laptop';

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[('E',)]

### Exercise: 9 (Serge I: 2002-11-02)

#### DB: "Computer firm"

Find the makers of PCs with a processor speed of 450 MHz or more. Result set: maker.

In [10]:
%%sql SELECT DISTINCT Product.maker 
FROM Product 
WHERE model IN (SELECT model
FROM PC
WHERE speed >= 450);

 * postgresql://postgres:***@localhost:5432/postgres
3 rows affected.


[('B',), ('E',), ('A',)]

### Exercise: 10 (Serge I: 2002-09-23)

#### DB: "Computer firm"

Find the printer models having the highest price. Result set: model, price.

In [11]:
%%sql SELECT model, price 
FROM Printer 
WHERE price = (SELECT MAX(price) 
               FROM Printer);

 * postgresql://postgres:***@localhost:5432/postgres
2 rows affected.


[('1276', Decimal('400.00')), ('1288', Decimal('400.00'))]

### Exercise: 11 (Serge I: 2002-11-02)

#### DB: "Computer firm"

Find out the average speed of PCs.

In [12]:
%%sql SELECT AVG(speed) 
FROM PC;

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[(Decimal('608.3333333333333333'),)]

### Exercise: 12 (Serge I: 2002-11-02)

#### DB: "Computer firm"

Find out the average speed of the laptops priced over $1000.

In [13]:
%%sql SELECT AVG(speed) AS Avg_Speed 
FROM Laptop 
WHERE price > 1000;

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[(Decimal('700.0000000000000000'),)]

### Exercise: 13 (Serge I: 2002-11-02)
#### DB: "Computer firm"

Find out the average speed of the PCs produced by maker A.

In [14]:
%%sql SELECT AVG(PC.speed) 
FROM PC
WHERE PC.model
IN (SELECT model
FROM Product
WHERE maker = 'A');

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[(Decimal('606.2500000000000000'),)]

### Exercise: 14 (Serge I: 2002-11-05)

#### DB:"Ships"

For the ships in the Ships table that have at least 10 guns, get the class, name, and country.

In [15]:
%%sql SELECT Ships.class
 ,Ships.name
 ,Classes.country  
FROM Ships
JOIN 
Classes ON Classes.class =  Ships.class
WHERE Classes.numGuns >=10;

 * postgresql://postgres:***@localhost:5432/postgres
5 rows affected.


[('Tennessee', 'California', 'USA'),
 ('North Carolina', 'North Carolina', 'USA'),
 ('Tennessee', 'Tennessee', 'USA'),
 ('North Carolina', 'Washington', 'USA'),
 ('North Carolina', 'South Dakota', 'USA')]

### Exercise: 15 (Serge I: 2003-02-03)

#### DB: "Computer firm"

Get hard drive capacities that are identical for two or more PCs. 
Result set: hd.

In [16]:
%%sql SELECT hd
FROM PC
GROUP BY hd
HAVING COUNT(hd) >= 2;

 * postgresql://postgres:***@localhost:5432/postgres
5 rows affected.


[(8.0,), (20.0,), (5.0,), (14.0,), (10.0,)]

### Exercise: 16 (Serge I: 2003-02-03)

#### DB: "Computer firm"

Get pairs of PC models with identical speeds and the same RAM capacity. Each resulting pair should be displayed only once, i.e. (i, j) but not (j, i). 
Result set: model with the bigger number, model with the smaller number, speed, and RAM.

In [17]:
%%sql SELECT DISTINCT A.model
 ,B.model 
 ,B.speed
 ,B.ram
FROM PC AS A
JOIN PC AS B ON A.speed = B.speed AND A.ram = B.ram
WHERE A.model > B.model;

 * postgresql://postgres:***@localhost:5432/postgres
3 rows affected.


[('1233', '1121', 750, 128),
 ('1233', '1232', 500, 64),
 ('1260', '1232', 500, 32)]

### Exercise: 17 (Serge I: 2003-02-03)

#### DB: "Computer firm"

Get the laptop models that have a speed smaller than the speed of any PC. 
Result set: type, model, speed.

In [18]:
%%sql SELECT DISTINCT Product.type
 ,A.model
 ,A.speed
FROM Laptop AS A
INNER JOIN
Product ON Product.model = A.model
WHERE A.speed < ALL(SELECT speed
FROM PC
);

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[('Laptop', '1298', 350)]

### Exercise: 18 (Serge I: 2003-02-03)

#### DB: "Computer firm"

Find the makers of the cheapest color printers.
Result set: maker, price.

In [19]:
%%sql SELECT DISTINCT Product.maker, Printer.price
FROM Product
JOIN Printer ON Product.model = Printer.model
WHERE Printer.color = 'y'
AND Printer.price =
(SELECT MIN(price)
FROM Printer
WHERE color = 'y');

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[('D', Decimal('270.00'))]

### Exercise: 19 (Serge I: 2003-02-13)

#### DB: "Computer firm"

For each maker having models in the Laptop table, find out the average screen size of the laptops he produces. 
Result set: maker, average screen size.

In [20]:
%%sql SELECT Product.maker AS Maker, AVG(Laptop.screen) AS Avg_screen
FROM Laptop
JOIN
Product ON Product.model = Laptop.model
GROUP BY Product.maker;

 * postgresql://postgres:***@localhost:5432/postgres
3 rows affected.


[('B', Decimal('14.0000000000000000')),
 ('C', Decimal('12.0000000000000000')),
 ('A', Decimal('13.0000000000000000'))]

### Exercise: 20 (Serge I: 2003-02-13)

#### DB: "Computer firm"

Find the makers producing at least three distinct models of PCs.
Result set: maker, number of PC models.

In [21]:
%%sql SELECT Product.maker AS Maker, COUNT(DISTINCT Product.model) AS Count
FROM Product
WHERE type = 'PC'
GROUP BY maker
HAVING COUNT(DISTINCT Product.model) >=3;

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[('E', 3)]

### Exercise: 21 (Serge I: 2003-02-13)

#### DB: "Computer firm"

Find out the maximum PC price for each maker having models in the PC table. Result set: maker, maximum price.

In [22]:
%%sql SELECT Product.maker, MAX(PC.price)
FROM Product
JOIN PC ON PC.model = Product.model
GROUP BY maker;

 * postgresql://postgres:***@localhost:5432/postgres
3 rows affected.


[('B', Decimal('850.00')), ('E', Decimal('350.00')), ('A', Decimal('980.00'))]

### Exercise: 22 (Serge I: 2003-02-13)

#### DB: "Computer firm"

For each value of PC speed that exceeds 600 MHz, find out the average price of PCs with identical speeds.
Result set: speed, average price.

In [23]:
%%sql SELECT speed, AVG(price) 
FROM PC
WHERE speed > 600
GROUP BY speed;

 * postgresql://postgres:***@localhost:5432/postgres
3 rows affected.


[(900, Decimal('980.0000000000000000')),
 (750, Decimal('900.0000000000000000')),
 (800, Decimal('970.0000000000000000'))]

### Exercise: 23 (Serge I: 2003-02-14)

#### DB: "Computer firm"

Get the makers producing both PCs having a speed of 750 MHz or higher and laptops with a speed of 750 MHz or higher. 
Result set: maker

In [24]:
%%sql SELECT DISTINCT Product.maker
FROM Product
JOIN PC ON PC.model = Product.model
WHERE PC.speed >= 750
INTERSECT
SELECT DISTINCT Product.maker
FROM Product
JOIN Laptop ON Laptop.model = Product.model
WHERE Laptop.speed >= 750;

 * postgresql://postgres:***@localhost:5432/postgres
2 rows affected.


[('B',), ('A',)]

### Exercise: 24 (Serge I: 2003-02-03)

#### DB: "Computer firm"

List the models of any type having the highest price of all products present in the database.

In [25]:
%%sql WITH MP AS( SELECT model, price FROM PC
UNION
SELECT model, price FROM Laptop
UNION
SELECT model, price FROM Printer)
SELECT model FROM MP
WHERE price = (SELECT MAX(price) FROM MP);

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[('1750',)]

### Exercise: 25 (Serge I: 2003-02-14)

#### DB: "Computer firm"

Find the printer makers also producing PCs with the lowest RAM capacity and the highest processor speed of all PCs having the lowest RAM capacity. 
Result set: maker.

In [26]:
%%sql WITH SR AS(SELECT model, speed FROM PC
WHERE ram IN(SELECT MIN(ram) FROM PC))
SELECT DISTINCT maker FROM Product
WHERE model IN (SELECT model FROM SR
WHERE speed IN (SELECT MAX(speed) FROM SR))
AND maker IN(SELECT maker FROM Product
WHERE type = 'Printer');

 * postgresql://postgres:***@localhost:5432/postgres
2 rows affected.


[('A',), ('E',)]

### Exercise: 26 (Serge I: 2003-02-14)

#### DB: "Computer firm"

Find out the average price of PCs and laptops produced by maker A.
Result set: one overall average price for all items.

In [27]:
%%sql WITH AP AS(SELECT Laptop.model, Laptop.price
FROM Laptop
JOIN 
Product ON Product.model = Laptop.model
WHERE Product.maker = 'A'
UNION ALL
SELECT PC.model, PC.price
FROM PC
JOIN 
Product ON Product.model = PC.model
WHERE Product.maker = 'A')
SELECT AVG(price) FROM AP;

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[(Decimal('754.1666666666666667'),)]

### Exercise: 27 (Serge I: 2003-02-03)

#### DB: "Computer firm"

Find out the average hard disk drive capacity of PCs produced by makers who also manufacture printers.
Result set: maker, average HDD capacity.

In [28]:
%%sql SELECT Product.maker, AVG(PC.hd) AS AVG_HDD
FROM Product
JOIN PC ON PC.model = Product.model
WHERE maker IN (SELECT maker
FROM Product
WHERE type = 'Printer')
GROUP BY maker;

 * postgresql://postgres:***@localhost:5432/postgres
2 rows affected.


[('A', 14.75), ('E', 10.0)]

### Exercise: 28 (Serge I: 2012-05-04)

#### DB: "Computer firm"

Using Product table, find out the number of makers who produce only one model.

In [29]:
%%sql WITH mc as (SELECT maker, COUNT(model) AS cm
FROM Product
GROUP BY maker)
SELECT COUNT(cm)
FROM mc
GROUP BY cm
HAVING cm=1;

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[(1,)]

### Exercise: 29 (Serge I: 2003-02-14)

#### DB:"Recycling firm"

Under the assumption that receipts of money (inc) and payouts (out) are registered not more than once a day for each collection point [i.e. the primary key consists of (point, date)], write a query displaying cash flow data (point, date, income, expense). 
Use Income_o and Outcome_o tables.

In [30]:
%%sql SELECT COALESCE(t1.point, t2.point), COALESCE(t1.date, t2.date), t1.inc, t2.out
FROM income_o t1
FULL JOIN outcome_o t2 ON t1.point = t2.point AND t1.date = t2.date;

 * postgresql://postgres:***@localhost:5432/postgres
19 rows affected.


[(1, datetime.datetime(2001, 3, 22, 0, 0), Decimal('15000.00'), None),
 (1, datetime.datetime(2001, 3, 23, 0, 0), Decimal('15000.00'), None),
 (1, datetime.datetime(2001, 3, 24, 0, 0), Decimal('3400.00'), Decimal('3663.00')),
 (1, datetime.datetime(2001, 4, 13, 0, 0), Decimal('5000.00'), Decimal('4490.00')),
 (1, datetime.datetime(2001, 5, 11, 0, 0), Decimal('4500.00'), Decimal('2530.00')),
 (2, datetime.datetime(2001, 3, 22, 0, 0), Decimal('10000.00'), Decimal('1440.00')),
 (2, datetime.datetime(2001, 3, 24, 0, 0), Decimal('1500.00'), None),
 (3, datetime.datetime(2001, 9, 13, 0, 0), Decimal('11500.00'), Decimal('1500.00')),
 (3, datetime.datetime(2001, 10, 2, 0, 0), Decimal('18000.00'), None),
 (3, datetime.datetime(2001, 9, 14, 0, 0), None, Decimal('2300.00')),
 (2, datetime.datetime(2001, 4, 2, 0, 0), None, Decimal('2040.00')),
 (2, datetime.datetime(2001, 3, 29, 0, 0), None, Decimal('7848.00')),
 (1, datetime.datetime(2001, 3, 14, 0, 0), None, Decimal('15348.00')),
 (1, datetime.datetime(2001, 3, 29, 0, 0), None, Decimal('2004.00')),
 (1, datetime.datetime(2001, 4, 11, 0, 0), None, Decimal('3195.04')),
 (3, datetime.datetime(2002, 9, 16, 0, 0), None, Decimal('2150.00')),
 (1, datetime.datetime(2001, 3, 26, 0, 0), None, Decimal('1221.00')),
 (1, datetime.datetime(2001, 4, 27, 0, 0), None, Decimal('3110.00')),
 (1, datetime.datetime(2001, 3, 28, 0, 0), None, Decimal('2075.00'))]

### Exercise: 30 (Serge I: 2003-02-14)

#### DB:"Recycling firm"

Under the assumption that receipts of money (inc) and payouts (out) can be registered any number of times a day for each collection point [i.e. the code column is the primary key], display a table with one corresponding row for each operating date of each collection point.
Result set: point, date, total payout per day (out), total money intake per day (inc). 
Missing values are considered to be NULL.

In [31]:
%%sql WITH IOC AS (SELECT t1.code, COALESCE(t1.point, t2.point) AS point, COALESCE(t1.date, t2.date) AS date, t1.inc, t2.out
FROM income t1
FULL JOIN outcome t2 ON t1.point = t2.point AND t1.date = t2.date AND t1.code = t2.code)
SELECT point, date, SUM(out), sum(inc) FROM IOC
GROUP BY date, point;

 * postgresql://postgres:***@localhost:5432/postgres
17 rows affected.


[(1, datetime.datetime(2001, 3, 24, 0, 0), Decimal('7163.00'), Decimal('7000.00')),
 (1, datetime.datetime(2001, 3, 22, 0, 0), None, Decimal('30000.00')),
 (1, datetime.datetime(2001, 3, 29, 0, 0), Decimal('4010.00'), None),
 (2, datetime.datetime(2001, 3, 29, 0, 0), Decimal('7848.00'), None),
 (1, datetime.datetime(2001, 4, 13, 0, 0), Decimal('4490.00'), Decimal('10000.00')),
 (1, datetime.datetime(2001, 3, 23, 0, 0), None, Decimal('15000.00')),
 (3, datetime.datetime(2001, 9, 13, 0, 0), Decimal('2700.00'), Decimal('3100.00')),
 (1, datetime.datetime(2001, 3, 28, 0, 0), Decimal('2075.00'), None),
 (1, datetime.datetime(2001, 4, 27, 0, 0), Decimal('3110.00'), None),
 (2, datetime.datetime(2001, 3, 24, 0, 0), None, Decimal('3000.00')),
 (1, datetime.datetime(2001, 4, 11, 0, 0), Decimal('3195.04'), None),
 (1, datetime.datetime(2001, 3, 26, 0, 0), Decimal('1221.00'), None),
 (1, datetime.datetime(2001, 3, 14, 0, 0), Decimal('15348.00'), None),
 (2, datetime.datetime(2001, 4, 2, 0, 0), Decimal('2040.00'), None),
 (2, datetime.datetime(2001, 3, 22, 0, 0), Decimal('2880.00'), Decimal('10000.00')),
 (3, datetime.datetime(2001, 9, 14, 0, 0), Decimal('1150.00'), None),
 (1, datetime.datetime(2001, 5, 11, 0, 0), Decimal('2530.00'), Decimal('4500.00'))]

### Exercise: 31 (Serge I: 2002-10-22)

#### DB:"Ships"

For ship classes with a gun caliber of 16 in. or more, display the class and the country.

In [32]:
%%sql SELECT class, country 
FROM Classes
WHERE bore >= 16;

 * postgresql://postgres:***@localhost:5432/postgres
3 rows affected.


[('Iowa', 'USA'), ('North Carolina', 'USA'), ('Yamato', 'Japan')]

### Exercise: 33 (Serge I: 2002-11-02)

#### DB:"Ships"

Get the ships sunk in the North Atlantic battle. 
Result set: ship.

In [33]:
%%sql SELECT ship 
FROM Outcomes
WHERE result = 'sunk'
AND battle = 'North Atlantic';

 * postgresql://postgres:***@localhost:5432/postgres
2 rows affected.


[('Bismarck',), ('Hood',)]

### Exercise: 34 (Serge I: 2002-11-04)

#### DB:"Ships"

In accordance with the Washington Naval Treaty concluded in the beginning of 1922, it was prohibited to build battle ships with a displacement of more than 35 thousand tons. 
Get the ships violating this treaty (only consider ships for which the year of launch is known). 
List the names of the ships.

In [34]:
%%sql SELECT s.name
FROM Ships s
FULL JOIN Classes c
On c.class = s.class
WHERE 1=1
AND c.displacement > 35000
AND c. type = 'bb'
AND s.launched >= 1922;

 * postgresql://postgres:***@localhost:5432/postgres
9 rows affected.


[('Iowa',),
 ('Missouri',),
 ('Musashi',),
 ('New Jersey',),
 ('North Carolina',),
 ('Washington',),
 ('Wisconsin',),
 ('Yamato',),
 ('South Dakota',)]

### Exercise: 35 (qwrqwr: 2012-11-23)

#### DB: "Computer firm"

Find models in the Product table consisting either of digits only or Latin letters (A-Z, case insensitive) only.
Result set: model, type.

MSSQL: correct

PGSQL: a few problems during validation

In [35]:
%%sql SELECT model, type
FROM product
WHERE upper(model) NOT like '%[^A-Z]%'
OR model NOT LIKE '%[^0-9]%';

 * postgresql://postgres:***@localhost:5432/postgres
16 rows affected.


[('1121', 'PC'),
 ('1232', 'PC'),
 ('1233', 'PC'),
 ('1260', 'PC'),
 ('1276', 'Printer'),
 ('1288', 'Printer'),
 ('1298', 'Laptop'),
 ('1321', 'Laptop'),
 ('1401', 'Printer'),
 ('1408', 'Printer'),
 ('1433', 'Printer'),
 ('1434', 'Printer'),
 ('1750', 'Laptop'),
 ('1752', 'Laptop'),
 ('2113', 'PC'),
 ('2112', 'PC')]

### Exercise: 36 (Serge I: 2003-02-17)

#### DB:"Ships"

List the names of lead ships in the database (including the Outcomes table).

In [36]:
%%sql SELECT name
FROM Ships s
JOIN Classes c
On s.name = c.class
UNION
SELECT o.ship AS name
FROM Outcomes o
JOIN Classes c 
ON o.ship = c.class;

 * postgresql://postgres:***@localhost:5432/postgres
8 rows affected.


[('Yamato',),
 ('Bismarck',),
 ('Revenge',),
 ('North Carolina',),
 ('Tennessee',),
 ('Kongo',),
 ('Renown',),
 ('Iowa',)]

### Exercise: 37 (Serge I: 2003-02-17)

#### DB:"Ships"

Find classes for which only one ship exists in the database (including the Outcomes table).

In [37]:
%%sql SELECT c.class 
FROM Classes c
LEFT JOIN (SELECT class, name 
FROM Ships
UNION
SELECT
Classes.class as class, Outcomes.ship as name
FROM Outcomes
JOIN Classes ON Outcomes.ship = Classes.class) as s ON c.class = s.class
GROUP BY c.class
HAVING COUNT(s.name)=1;

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[('Bismarck',)]

### Exercise: 38 (Serge I: 2003-02-19)

#### DB:"Ships"

Find countries that ever had classes of both battleships (‘bb’) and cruisers (‘bc’).

In [38]:
%%sql SELECT country FROM Classes
WHERE type = 'bb'
INTERSECT
SELECT country FROM Classes
WHERE type = 'bc';

 * postgresql://postgres:***@localhost:5432/postgres
2 rows affected.


[('Gt.Britain',), ('Japan',)]

### Exercise: 39 (Serge I: 2003-02-14)

#### DB:"Ships"

Find the ships that `survived for future battles`; that is, after being damaged in a battle, they participated in another one, which occurred later.

In [39]:
%%sql SELECT DISTINCT o.ship
FROM Outcomes o
JOIN Battles b
ON b.name = o.battle
WHERE 1 = 1
AND o.ship IN (SELECT o1.ship
FROM Outcomes o1
JOIN Battles b1
ON b1.name = o1.battle
WHERE 1 = 1
AND o1.result = 'damaged'
AND b.date > b1.date);

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[('California',)]

### Exercise: 40 (Serge I: 2012-04-20)

#### DB: "Computer firm"

Get the makers who produce only one product type and more than one model. Output: maker, type.

In [40]:
%%sql SELECT maker, MAX(type) AS type
FROM Product
GROUP BY maker
HAVING COUNT(DISTINCT type) = 1 AND COUNT(DISTINCT model) > 1;

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[('D', 'Printer')]

### Exercise: 41 (Serge I: 2019-05-31)

#### DB: "Computer firm"

For each maker who has models at least in one of the tables PC, Laptop, or Printer, determine the maximum price for his products. 
Output: maker; if there are NULL values among the prices for the products of a given maker, display NULL for this maker, otherwise, the maximum price.

In [41]:
%%sql WITH mp AS (
SELECT model
 ,price
FROM PC
UNION
SELECT model
 ,price
FROM Printer
UNION
SELECT model
 ,price
FROM Laptop)

SELECT DISTINCT p.maker
 ,CASE WHEN MAX(CASE WHEN mp.price IS NULL THEN 1 ELSE 0 END) = 0 
THEN MAX(mp.price) END AS m_price
FROM mp
LEFT JOIN Product p
ON mp.model = p.model
GROUP BY p.maker;

 * postgresql://postgres:***@localhost:5432/postgres
5 rows affected.


[('B', Decimal('1200.00')),
 ('A', Decimal('1150.00')),
 ('E', Decimal('350.00')),
 ('D', Decimal('400.00')),
 ('C', Decimal('970.00'))]

### Exercise: 42 (Serge I: 2002-11-05)

#### DB:"Ships"

Find the names of ships sunk at battles, along with the names of the corresponding battles.

In [42]:
%%sql SELECT ship
 ,battle
FROM Outcomes
WHERE result = 'sunk';

 * postgresql://postgres:***@localhost:5432/postgres
6 rows affected.


[('Bismarck', 'North Atlantic'),
 ('Fuso', 'Surigao Strait'),
 ('Hood', 'North Atlantic'),
 ('Kirishima', 'Guadalcanal'),
 ('Schamhorst', 'North Cape'),
 ('Yamashiro', 'Surigao Strait')]

### Exercise: 43 (qwrqwr: 2011-10-28)

#### DB:"Ships"

Get the battles that occurred in years when no ships were launched into water.

In [43]:
%%sql SELECT b.name FROM Battles b
WHERE 1 = 1
AND EXTRACT(YEAR FROM b.date) NOT IN (
SELECT DISTINCT launched 
FROM Ships
WHERE launched IS NOT NULL);


 * postgresql://postgres:***@localhost:5432/postgres
2 rows affected.


[('#Cuba62a',), ('#Cuba62b',)]

### Exercise: 44 (Serge I: 2002-12-04)

#### DB:"Ships"

Find all ship names beginning with the letter R.

In [44]:
%%sql SELECT DISTINCT name
FROM Ships
WHERE name LIKE 'R%'
UNION
SELECT DISTINCT ship AS name
FROM Outcomes
WHERE ship LIKE 'R%';

 * postgresql://postgres:***@localhost:5432/postgres
8 rows affected.


[('Rodney',),
 ('Renown',),
 ('Royal Oak',),
 ('Resolution',),
 ('Ramillies',),
 ('Repulse',),
 ('Royal Sovereign',),
 ('Revenge',)]

### Exercise: 45 (Serge I: 2002-12-04)

#### DB:"Ships"

Find all ship names consisting of three or more words (e.g., King George V).

Consider the words in ship names to be separated by single spaces, and the ship names to have no leading or trailing spaces

In [45]:
%%sql SELECT name
FROM Ships
WHERE name LIKE '% % %'
UNION
SELECT ship AS name
FROM Outcomes
WHERE ship LIKE '% % %';

 * postgresql://postgres:***@localhost:5432/postgres
3 rows affected.


[('Prince of Wales',), ('King George V',), ('Duke of York',)]

### Exercise: 46 (Serge I: 2003-02-14)

#### DB:"Ships"

For each ship that participated in the Battle of Guadalcanal, get its name, displacement, and the number of guns.

In [46]:
%%sql WITH ndng AS (SELECT s.name
 ,c.displacement
 ,c.numguns
FROM Ships s
JOIN Classes c
ON s.class = c.class
UNION
SELECT class AS name
 ,displacement
 ,numguns
FROM Classes)
SELECT o.ship
 ,ndng. displacement
 ,ndng.numguns
FROM Outcomes o
LEFT JOIN ndng
ON o.ship = ndng.name
WHERE battle = 'Guadalcanal';

 * postgresql://postgres:***@localhost:5432/postgres
4 rows affected.


[('California', 32000, 12),
 ('Washington', 37000, 12),
 ('Kirishima', 32000, 8),
 ('South Dakota', 37000, 12)]

### Exercise: 48 (Serge I: 2003-02-16)

#### DB:"Ships"

Find the ship classes having at least one ship sunk in battles.

In [47]:
%%sql WITH cr AS (SELECT c.class
 ,o.result
FROM Outcomes o
JOIN Classes c
ON c.class = o.ship
UNION ALL
SELECT s.class
 ,o.result
FROM Ships s
JOIN Outcomes o
ON s.name = o.ship)
SELECT DISTINCT class
FROM cr
WHERE 1 = 1
AND result = 'sunk';

 * postgresql://postgres:***@localhost:5432/postgres
2 rows affected.


[('Bismarck',), ('Kongo',)]

### Exercise: 49 (Serge I: 2003-02-17)

#### DB:"Ships"

Find the names of the ships having a gun caliber of 16 inches (including ships in the Outcomes table).

In [48]:
%%sql SELECT s.name
FROM Ships s
JOIN Classes c
ON s.class = c.class
WHERE c.bore = 16
UNION
SELECT o.ship AS name
FROM Outcomes o
JOIN Classes c
ON o.ship = c.class
WHERE c.bore = 16;

 * postgresql://postgres:***@localhost:5432/postgres
7 rows affected.


[('New Jersey',),
 ('Iowa',),
 ('Missouri',),
 ('North Carolina',),
 ('South Dakota',),
 ('Washington',),
 ('Wisconsin',)]

### Exercise: 50 (Serge I: 2002-11-05)

#### DB:"Ships"

Find the battles in which Kongo-class ships from the Ships table were engaged.

In [49]:
%%sql SELECT DISTINCT o.battle
FROM Ships s
JOIN Outcomes o
ON s.name = o.ship
WHERE s.class = 'Kongo';

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[('Guadalcanal',)]

### Exercise: 65 (Serge I: 2009-08-24)

#### DB: "Computer firm"

Number the unique pairs {maker, type} in the Product table, ordering them as follows:
- maker name in ascending order;
- type of product (type) in the order PC, Laptop, Printer.

If a manufacturer produces more than one type of product, its name should be displayed in the first row only;
other rows for THIS manufacturer should contain an empty string (').

In [50]:
%%sql WITH UPair AS (SELECT DISTINCT maker, type, LENGTH(type) LT,
RANK() OVER (PARTITION BY maker ORDER BY LENGTH(type)) rank
FROM Product)
SELECT ROW_NUMBER() OVER(ORDER BY maker, LENGTH(type)) num,
CASE
WHEN rank >= 2
THEN ''
ELSE maker
END maker,
type
FROM UPair;

 * postgresql://postgres:***@localhost:5432/postgres
9 rows affected.


[(1, 'A', 'PC'),
 (2, '', 'Laptop'),
 (3, '', 'Printer'),
 (4, 'B', 'PC'),
 (5, '', 'Laptop'),
 (6, 'C', 'Laptop'),
 (7, 'D', 'Printer'),
 (8, 'E', 'PC'),
 (9, '', 'Printer')]

### Exercise: 83 (dorin_larsen: 2006-03-14)

#### DB:"Ships"

Find out the names of the ships in the Ships table that meet at least four criteria from the following list:

numGuns = 8, 

bore = 15,

displacement = 32000,

type = bb,

launched = 1915,

class = Kongo,

country = USA.

In [51]:
%%sql SELECT S.name FROM Classes C
JOIN Ships S ON S.class = C.class
WHERE 1=1
AND 4 <= (CASE WHEN C.numGuns = 8 THEN 1 ELSE 0 END +
CASE WHEN C.bore = 15 THEN 1 ELSE 0 END +
CASE WHEN C.displacement = 32000 THEN 1 ELSE 0 END +
CASE WHEN C.type = 'bb' THEN 1 ELSE 0 END +
CASE WHEN S.launched = 1915 THEN 1 ELSE 0 END +
CASE WHEN s.class = 'Kongo' THEN 1 ELSE 0 END +
CASE WHEN C.country = 'USA' THEN 1 ELSE 0 END);

 * postgresql://postgres:***@localhost:5432/postgres
1 rows affected.


[('Kirishima',)]

### Exercise: 105 (qwrqwr: 2013-09-11)

#### DB: "Computer firm"

Statisticians Alice, Betty, Carol and Diana are numbering rows in the Product table.

Initially, all of them have sorted the table rows in ascending order by the names of the makers.

Alice assigns a new number to each row, sorting the rows belonging to the same maker by model in ascending order.

The other three statisticians assign identical numbers to all rows having the same maker.

Betty assigns the numbers starting with one, increasing the number by 1 for each next maker.

Carol gives a maker the same number the row with this maker's first model receives from Alice.

Diana assigns a maker the same number the row with this maker's last model receives from Alice.

Output: maker, model, row numbers assigned by Alice, Betty, Carol, and Diana respectively.

In [52]:
%%sql SELECT maker, model,
       ROW_NUMBER() OVER (ORDER BY maker, model) A,
       DENSE_RANK() OVER (ORDER BY maker) B,
       RANK() OVER (ORDER BY maker) C,
       COUNT(*) OVER (ORDER BY maker) D
FROM product;

 * postgresql://postgres:***@localhost:5432/postgres
16 rows affected.


[('A', '1232', 1, 1, 1, 7),
 ('A', '1233', 2, 1, 1, 7),
 ('A', '1276', 3, 1, 1, 7),
 ('A', '1298', 4, 1, 1, 7),
 ('A', '1401', 5, 1, 1, 7),
 ('A', '1408', 6, 1, 1, 7),
 ('A', '1752', 7, 1, 1, 7),
 ('B', '1121', 8, 2, 8, 9),
 ('B', '1750', 9, 2, 8, 9),
 ('C', '1321', 10, 3, 10, 10),
 ('D', '1288', 11, 4, 11, 12),
 ('D', '1433', 12, 4, 11, 12),
 ('E', '1260', 13, 5, 13, 16),
 ('E', '1434', 14, 5, 13, 16),
 ('E', '2112', 15, 5, 13, 16),
 ('E', '2113', 16, 5, 13, 16)]

### Exercise: 109 (qwrqwr: 2011-01-13)

#### DB:"Painting"

Display:
1. The names of all squares that are black or white.
2. The total number of white squares.
3. The total number of black squares.

In [53]:
%%sql WITH WB AS(SELECT utQ.Q_NAME, SUM(utB.B_VOL)/765 AS C
FROM utB
FULL JOIN utQ ON utB.B_Q_ID = utQ.Q_ID
GROUP BY Q_NAME
HAVING SUM(utB.B_VOL) = 765 OR SUM(utB.B_VOL) IS NULL)
SELECT Q_NAME,
SUM(C) OVER() AS WHITES,
(COUNT(Q_NAME) OVER()) - (SELECT SUM(C) FROM WB) AS BLACKS
FROM WB
ORDER BY 1;

 * postgresql://postgres:***@localhost:5432/postgres
12 rows affected.


[('Square # 01', Decimal('10'), Decimal('2')),
 ('Square # 02', Decimal('10'), Decimal('2')),
 ('Square # 03', Decimal('10'), Decimal('2')),
 ('Square # 05', Decimal('10'), Decimal('2')),
 ('Square # 06', Decimal('10'), Decimal('2')),
 ('Square # 07', Decimal('10'), Decimal('2')),
 ('Square # 09', Decimal('10'), Decimal('2')),
 ('Square # 10', Decimal('10'), Decimal('2')),
 ('Square # 11', Decimal('10'), Decimal('2')),
 ('Square # 12', Decimal('10'), Decimal('2')),
 ('Square # 23', Decimal('10'), Decimal('2')),
 ('Square # 25', Decimal('10'), Decimal('2'))]